"""Google Cloud Run deployment configuration."""
from __future__ import annotations


def generate_cloudbuild_yaml() -> str:
    return """# Cloud Build configuration
# Auto-generated by `dataportal publish`
# Deploy: gcloud builds submit --config cloudbuild.yaml .

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA', '.']

  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/dataportal:latest']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dataportal:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dataportal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '${_PORT}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'

substitutions:
  _REGION: us-central1
  _PORT: '8001'

images:
  - 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/dataportal:latest'

options:
  logging: CLOUD_LOGGING_ONLY
"""


def generate_deploy_script(port: int = 8001) -> str:
    return f"""#!/bin/bash
# Deploy DataPortal to Google Cloud Run
# Auto-generated by `dataportal publish`
set -e

PROJECT_ID="${{PROJECT_ID:-$(gcloud config get-value project)}}"
REGION="${{REGION:-us-central1}}"
SERVICE_NAME="${{SERVICE_NAME:-dataportal}}"
PORT={port}

echo "Deploying DataPortal to Cloud Run..."
echo "  Project: $PROJECT_ID"
echo "  Region:  $REGION"
echo "  Service: $SERVICE_NAME"
echo ""

# Build and push
echo "Building container image..."
gcloud builds submit --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME" .

# Deploy
echo "Deploying to Cloud Run..."
gcloud run deploy "$SERVICE_NAME" \\
    --image "gcr.io/$PROJECT_ID/$SERVICE_NAME" \\
    --region "$REGION" \\
    --platform managed \\
    --allow-unauthenticated \\
    --port "$PORT" \\
    --memory 512Mi \\
    --cpu 1 \\
    --min-instances 0 \\
    --max-instances 3

# Get URL
URL=$(gcloud run services describe "$SERVICE_NAME" --region="$REGION" --format='value(status.url)')
echo ""
echo "Deployment complete!"
echo "Service URL: $URL"
echo ""
echo "View logs:"
echo "  gcloud run services logs read $SERVICE_NAME --region=$REGION"
echo ""
echo "Rollback:"
echo "  ./rollback.sh $SERVICE_NAME $REGION"
"""
