"""Google Cloud Run deployment configuration."""
from __future__ import annotations


def generate_cloudbuild_yaml() -> str:
    return """# Cloud Build configuration
# Auto-generated by `dataportal publish`
# Deploy: gcloud builds submit --config cloudbuild.yaml .

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA', '.']

  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/dataportal:latest']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dataportal:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dataportal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '${_PORT}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'

substitutions:
  _REGION: us-central1
  _PORT: '8001'

images:
  - 'gcr.io/$PROJECT_ID/dataportal:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/dataportal:latest'

options:
  logging: CLOUD_LOGGING_ONLY
"""


def generate_deploy_script(port: int = 8001) -> str:
    return f"""#!/bin/bash
# Deploy DataPortal to Google Cloud Run
# Auto-generated by `dataportal publish`
set -e

PROJECT_ID="${{PROJECT_ID:-$(gcloud config get-value project 2>/dev/null)}}"
REGION="${{REGION:-us-central1}}"
SERVICE_NAME="${{SERVICE_NAME:-dataportal}}"
PORT={port}

if [ -z "$PROJECT_ID" ]; then
    echo "Error: PROJECT_ID not set and gcloud not configured."
    echo "Run: gcloud config set project YOUR_PROJECT_ID"
    exit 1
fi

echo "=== Deploying DataPortal to Cloud Run ==="
echo "  Project: $PROJECT_ID"
echo "  Region:  $REGION"
echo "  Service: $SERVICE_NAME"
echo "  Port:    $PORT"
echo ""

# Build and push
echo "[1/3] Building container image..."
gcloud builds submit --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME" . --quiet

# Deploy
echo "[2/3] Deploying to Cloud Run..."
gcloud run deploy "$SERVICE_NAME" \\
    --image "gcr.io/$PROJECT_ID/$SERVICE_NAME" \\
    --region "$REGION" \\
    --platform managed \\
    --allow-unauthenticated \\
    --port "$PORT" \\
    --memory 512Mi \\
    --cpu 1 \\
    --min-instances 0 \\
    --max-instances 3 \\
    --set-env-vars="DATAPORTAL_SOURCES=/app/data,DATAPORTAL_CONFIG=/app/config.json" \\
    --quiet

# Get URL
echo "[3/3] Verifying deployment..."
URL=$(gcloud run services describe "$SERVICE_NAME" --region="$REGION" --format='value(status.url)')
echo ""
echo "=== Deployment complete ==="
echo "Service URL: $URL"
echo "Health check: $URL/health"
echo ""

# Quick health check
HTTP_CODE=$(curl -s -o /dev/null -w "%{{http_code}}" "$URL/health" 2>/dev/null || echo "000")
if [ "$HTTP_CODE" = "200" ]; then
    echo "Health check: PASSED"
else
    echo "Health check: PENDING (service may still be starting, code=$HTTP_CODE)"
fi
"""


def generate_cloudrun_logs_script() -> str:
    return """#!/bin/bash
# View DataPortal logs on Cloud Run
# Auto-generated by `dataportal publish`
set -e

SERVICE_NAME="${SERVICE_NAME:-dataportal}"
REGION="${REGION:-us-central1}"
LINES="${1:-100}"

echo "=== Cloud Run logs for $SERVICE_NAME ==="
echo "Region: $REGION | Lines: $LINES"
echo ""

gcloud run services logs read "$SERVICE_NAME" \
    --region="$REGION" \
    --limit="$LINES" \
    --format="value(timestamp.date(), severity, textPayload)"

echo ""
echo "--- Live tail: gcloud run services logs tail $SERVICE_NAME --region=$REGION ---"
"""


def generate_cloudrun_rollback_script() -> str:
    return """#!/bin/bash
# Rollback DataPortal on Cloud Run to a previous revision
# Auto-generated by `dataportal publish`
set -e

SERVICE_NAME="${SERVICE_NAME:-dataportal}"
REGION="${REGION:-us-central1}"

echo "=== Cloud Run Rollback: $SERVICE_NAME ==="
echo ""

# List recent revisions
echo "Recent revisions:"
gcloud run revisions list \
    --service="$SERVICE_NAME" \
    --region="$REGION" \
    --limit=5 \
    --format="table(name, active.yesno(yes='SERVING',no=''), createTime.date(), image)"

echo ""

# Get the second revision (previous) as default
PREV_REVISION=$(gcloud run revisions list \
    --service="$SERVICE_NAME" \
    --region="$REGION" \
    --limit=2 \
    --format="value(name)" | tail -1)

if [ -z "$PREV_REVISION" ]; then
    echo "No previous revision found."
    exit 1
fi

read -p "Rollback to revision [$PREV_REVISION]: " REVISION
REVISION="${REVISION:-$PREV_REVISION}"

echo ""
echo "Rolling back to: $REVISION"
gcloud run services update-traffic "$SERVICE_NAME" \
    --region="$REGION" \
    --to-revisions="$REVISION=100"

echo ""
echo "=== Rollback complete ==="
echo "All traffic now routed to: $REVISION"

# Verify
URL=$(gcloud run services describe "$SERVICE_NAME" --region="$REGION" --format='value(status.url)')
echo "Service URL: $URL"
"""
