"""docker-compose.yml generation."""
from __future__ import annotations


def generate_compose(port: int = 8001) -> str:
    return f"""# DataPortal Docker Compose
# Auto-generated by `dataportal publish`
#
# Usage:
#   cp secrets.env.example secrets.env  # fill in real values
#   docker compose up --build

services:
  dataportal:
    build: .
    ports:
      - "{port}:{port}"
    environment:
      - PORT={port}
      - DATAPORTAL_SOURCES=/app/data
      - DATAPORTAL_CONFIG=/app/config.json
    env_file:
      - secrets.env
    volumes:
      - dataportal-data:/app/data
    secrets:
      - dataportal_env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:{port}/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  dataportal_env:
    file: ./secrets.env

volumes:
  dataportal-data:
    driver: local
"""
