"""docker-compose.yml generation."""
from __future__ import annotations


def generate_compose(port: int = 8001) -> str:
    return f"""# DataPortal Docker Compose
# Auto-generated by `dataportal publish`

services:
  dataportal:
    build: .
    ports:
      - "{port}:{port}"
    environment:
      - PORT={port}
      - DATAPORTAL_SOURCES=/app/data
      - DATAPORTAL_CONFIG=/app/config.json
    volumes:
      - dataportal-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:{port}/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  dataportal-data:
    driver: local
"""
