"""Dockerfile generation."""
from __future__ import annotations


def generate_dockerfile(
    port: int = 8001,
    include_data: bool = True,
    sources: list[str] | None = None,
    config_path: str | None = None,
) -> str:
    data_copy = ""
    if include_data:
        data_copy = "COPY data/ /app/data/"

    config_copy = ""
    config_env = ""
    if config_path:
        config_copy = "COPY config.json /app/config.json"
        config_env = 'ENV DATAPORTAL_CONFIG="/app/config.json"'

    sources_env = ""
    if include_data:
        sources_env = 'ENV DATAPORTAL_SOURCES="/app/data"'

    return f"""# DataPortal - Production Deployment
# Auto-generated by `dataportal publish`

FROM python:3.12-slim AS builder

WORKDIR /build
COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir --prefix=/install .

FROM python:3.12-slim

WORKDIR /app

# Copy installed packages
COPY --from=builder /install /usr/local

# Copy application
COPY src/ /app/src/
COPY pyproject.toml /app/

{data_copy}
{config_copy}

# Environment
ENV PORT={port}
{sources_env}
{config_env}

# Non-root user
RUN useradd --create-home appuser
USER appuser

EXPOSE {port}

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:{port}/health')"

CMD ["python", "-m", "dataportal", "serve", "--host", "0.0.0.0", "--port", "{port}"]
"""
