"""Render.com deployment configuration."""
from __future__ import annotations


def generate_render_yaml(port: int = 8001) -> str:
    return f"""# Render Blueprint
# Auto-generated by `dataportal publish`
# Deploy: connect this repo to Render and it will auto-detect render.yaml

services:
  - type: web
    name: dataportal
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "{port}"
      - key: DATAPORTAL_SOURCES
        value: /app/data
      - key: DATAPORTAL_CONFIG
        value: /app/config.json
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DP_AUTH_TOKENS
        sync: false
      - key: DP_SITE_TITLE
        sync: false
    disk:
      name: dataportal-data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
"""


def generate_render_deploy_script(port: int = 8001) -> str:
    return f"""#!/bin/bash
# Deploy DataPortal to Render.com
# Auto-generated by `dataportal publish`
set -e

SERVICE_NAME="${{SERVICE_NAME:-dataportal}}"
RENDER_API_KEY="${{RENDER_API_KEY:?Set RENDER_API_KEY env var}}"
REPO_URL="${{REPO_URL:?Set REPO_URL to your git repo URL}}"

echo "=== Deploying DataPortal to Render ==="
echo "Service: $SERVICE_NAME"
echo ""

# Check if service exists
echo "Checking for existing service..."
EXISTING=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \\
    "https://api.render.com/v1/services?name=$SERVICE_NAME&limit=1" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if data: print(data[0]['service']['id'])
" 2>/dev/null || echo "")

if [ -n "$EXISTING" ]; then
    echo "Service found: $EXISTING"
    echo "Triggering deploy..."
    curl -s -X POST "https://api.render.com/v1/services/$EXISTING/deploys" \\
        -H "Authorization: Bearer $RENDER_API_KEY" \\
        -H "Content-Type: application/json" \\
        -d '{{"clearCache": "do_not_clear"}}' | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(f\\"Deploy triggered: {{data.get('id', 'unknown')}}\\")
print(f\\"Status: {{data.get('status', 'pending')}}\\")
"
else
    echo "Creating new service..."
    curl -s -X POST "https://api.render.com/v1/services" \\
        -H "Authorization: Bearer $RENDER_API_KEY" \\
        -H "Content-Type: application/json" \\
        -d "$(cat <<ENDJSON
{{
  "type": "web_service",
  "name": "$SERVICE_NAME",
  "repo": "$REPO_URL",
  "autoDeploy": "yes",
  "serviceDetails": {{
    "runtime": "docker",
    "dockerfilePath": "./Dockerfile",
    "envVars": [
      {{"key": "PORT", "value": "{port}"}},
      {{"key": "DATAPORTAL_SOURCES", "value": "/app/data"}}
    ],
    "plan": "starter",
    "healthCheckPath": "/health"
  }}
}}
ENDJSON
)" | python3 -c "
import sys, json
data = json.load(sys.stdin)
svc = data.get('service', {{}})
print(f\\"Service created: {{svc.get('id', 'unknown')}}\\")
print(f\\"URL: https://{{svc.get('serviceDetails', {{}}).get('url', 'pending...')}}\\")
"
fi

echo ""
echo "=== Done ==="
echo "View logs: ./logs.sh"
echo "Rollback:  ./rollback.sh"
"""


def generate_render_logs_script() -> str:
    return """#!/bin/bash
# View DataPortal logs on Render
# Auto-generated by `dataportal publish`
set -e

SERVICE_NAME="${SERVICE_NAME:-dataportal}"
RENDER_API_KEY="${RENDER_API_KEY:?Set RENDER_API_KEY env var}"

# Find service ID
SERVICE_ID=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
    "https://api.render.com/v1/services?name=$SERVICE_NAME&limit=1" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if data: print(data[0]['service']['id'])
else: sys.exit(1)
")

if [ -z "$SERVICE_ID" ]; then
    echo "Error: Service '$SERVICE_NAME' not found"
    exit 1
fi

echo "=== Logs for $SERVICE_NAME ($SERVICE_ID) ==="
echo ""

# Fetch recent logs
curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
    "https://api.render.com/v1/services/$SERVICE_ID/logs?limit=100" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for entry in data:
    ts = entry.get('timestamp', '')[:19]
    msg = entry.get('message', '')
    print(f'{ts} {msg}')
"
"""


def generate_render_rollback_script() -> str:
    return """#!/bin/bash
# Rollback DataPortal on Render to a previous deploy
# Auto-generated by `dataportal publish`
set -e

SERVICE_NAME="${SERVICE_NAME:-dataportal}"
RENDER_API_KEY="${RENDER_API_KEY:?Set RENDER_API_KEY env var}"

# Find service ID
SERVICE_ID=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
    "https://api.render.com/v1/services?name=$SERVICE_NAME&limit=1" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if data: print(data[0]['service']['id'])
else: sys.exit(1)
")

if [ -z "$SERVICE_ID" ]; then
    echo "Error: Service '$SERVICE_NAME' not found"
    exit 1
fi

echo "=== Recent deploys for $SERVICE_NAME ==="
echo ""

# List recent deploys
curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
    "https://api.render.com/v1/services/$SERVICE_ID/deploys?limit=5" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for i, d in enumerate(data):
    status = d.get('status', 'unknown')
    commit = d.get('commit', {}).get('id', 'N/A')[:8]
    created = d.get('createdAt', '')[:19]
    deploy_id = d.get('id', '')
    marker = ' (current)' if i == 0 else ''
    print(f'  [{i}] {deploy_id} | {created} | {commit} | {status}{marker}')
"

echo ""
read -p "Enter deploy index to rollback to (1-4): " IDX

DEPLOY_ID=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
    "https://api.render.com/v1/services/$SERVICE_ID/deploys?limit=5" | python3 -c "
import sys, json
data = json.load(sys.stdin)
idx = int(sys.argv[1])
if 0 <= idx < len(data):
    print(data[idx]['id'])
" "$IDX")

if [ -n "$DEPLOY_ID" ]; then
    echo "Rolling back to deploy $DEPLOY_ID..."
    curl -s -X POST "https://api.render.com/v1/services/$SERVICE_ID/rollback/$DEPLOY_ID" \
        -H "Authorization: Bearer $RENDER_API_KEY"
    echo ""
    echo "Rollback initiated."
else
    echo "Invalid selection, aborting."
    exit 1
fi
"""
