"""Render.com deployment configuration."""
from __future__ import annotations


def generate_render_yaml(port: int = 8001) -> str:
    return f"""# Render Blueprint
# Auto-generated by `dataportal publish`
# Deploy: connect this repo to Render and it will auto-detect render.yaml

services:
  - type: web
    name: dataportal
    runtime: python
    buildCommand: pip install .
    startCommand: dataportal serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: "{port}"
      - key: DATAPORTAL_SOURCES
        value: /app/data
      - key: DATAPORTAL_CONFIG
        value: /app/config.json
      - key: PYTHON_VERSION
        value: "3.12"
    disk:
      name: dataportal-data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true
    plan: free
"""
